import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-primary">InCard</h1>

        <Image
          src="/logo.png"
          width="100"
          height="30"
          alt="incard grey logo with white background"
        />
      </main>
    </div>
  );
};

export default Home;
